---
- name: Check if directory exists
  stat:
    path: "{{ os_config_dir }}"
  register: path_check

- name: "Fail if the configs directory does not exist"
  fail:
    msg: "Configs directory does not exist"
  when: not path_check.stat.exists

- name: Get OAuth cluster configuration for IDP and Secret Name
  kubernetes.core.k8s_info:
    api_version: config.openshift.io/v1
    kind: OAuth
    name: cluster
  register: oauth_cluster_data

- name: Set IDP Name for later use if it exists otherwise use default idp name
  set_fact:
    idp_name: "{{ oauth_cluster_data.resources[0].spec.identityProviders | default([]) | json_query('[].name') | first | default('Local') }}"

- name: Print Identity Provider Name
  debug:
    var: idp_name

- name: Set fact to check if secret exists in oauth config
  set_fact:
    is_secret_exist: "{{ oauth_cluster_data.resources[0].spec.identityProviders | default('') | json_query('[].name') }}"

- name: Set Secret Name for later use if it exists otherwise use default secret name
  set_fact:
    secret_name: "{{ oauth_cluster_data.resources[0].spec.identityProviders | default([]) | json_query('[].htpasswd.fileData.name') | first | default('htpasswd') }}"

- name: Set this flag if existing secret is present
  set_fact:
    existed_secret: true
  when: is_secret_exist | length > 0

- name: Print Secret Name
  debug:
    var: secret_name

- name: Print Existed Secret Flag
  debug:
    var: existed_secret
