- name: Extract OpenShift Config Secret to get exist user from htpasswd data
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    namespace: "{{ openshift_config_ns }}"
    name: "{{ secret_name }}"
  register: secret_data

- name: Print Secret Data
  debug:
    var: secret_data

- name: Decode htpasswd value
  set_fact:
    decoded_htpasswd: "{{ secret_data.resources[0].data.htpasswd | b64decode | string }}"
- name: Print decoded htpasswd value
  debug:
    var: decoded_htpasswd

- name: "Save existing htpasswd user and password to {{ os_config_dir }}/users.htpasswd"
  copy:
    content: "{{ decoded_htpasswd }}"
    dest: "{{ os_config_dir }}/users.htpasswd"
    mode: '0640'
