---
- name: Install httpd-tools package
  become: true
  package:
    name: httpd-tools
    state: present
  register: httpd_tools_pkg

- name: Display whether httpd-tools is installed or not
  debug:
    var: httpd_tools_pkg

- name: Check if users.htpasswd file exists in {{ os_config_dir }}
  stat:
    path: "{{ os_config_dir }}/users.htpasswd"
  register: users_htpasswd_file

- name: Generate htpasswd entry and append or create users.htpasswd
  become: true
  command: "{{ 'htpasswd -bB' if users_htpasswd_file.stat.exists else 'htpasswd -cBb' }} {{ os_config_dir }}/users.htpasswd {{ admin_user }} {{ admin_passwd }}"
  when: httpd_tools_pkg.rc == 0  # Only run if httpd-tools is installed
  register: htpasswd_output
  failed_when: htpasswd_output.rc != 0

- name: Print htpasswd file after generation
  debug:
    var: htpasswd_output

- name: Encoding the htpasswd file from {{ os_config_dir }}/users.htpasswd
  slurp:
    src: "{{ os_config_dir }}/users.htpasswd"
  register: htpasswd_encoded

#- name: Encoding the htpasswd file from {{ os_config_dir }}/users.htpasswd
#  set_fact:
#    htpasswd_encoded: "{{ lookup('file', os_config_dir + '/users.htpasswd') | b64encode }}"  
#  register: htpasswd_encoded

- name: Set htpasswd encoded for later use in Oauth 
  set_fact:
    htpasswd_encoded: "{{ htpasswd_encoded.content }}"

- name: Print htpasswd encoded password content
  debug:
    var: htpasswd_encoded
...
