---
- name: Get Openshift Console Route Information 
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: Route
    namespace: "{{ openshift_console_ns }}"
  register: route_info

- name: Display route information
  debug:
    var: route_info

- name: Disable Openshift Console Gui
  block:
    - name: Start Disable Openshift Console Gui by PATCH Console CR
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'disable_openshift_console.yaml') }}"
        register: remove_console_gui

    - name: Display Console result after it got removed
      debug:
        var: remove_console_gui

    - name: Check if console pods are removed from {{ openshift_console_ns }}
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: "{{ openshift_console_ns }}"
        register: pod_list
      until: pod_list.resources | length == 0
      retries: 30
      delay: 5

    - name: Display pods list information
      debug:
        var: pod_list

  when: route_info.resources | default([]) | length > 0

- name: Display Console GUI is already disabled Message
  debug:
    msg: "Console GUI is already disabled"
  when: route_info.resources | default([]) | length == 0
...
